export const GET_ALL_EXERCISES = 'EXERCISES/GET_ALL_EXERCISES'
export const SET_ALL_EXERCISES = 'EXERCISES/SET_ALL_EXERCISES'
export const SET_CREATE_EXERCISE_WINDOW = 'EXERCISES/SET_CREATE_EXERCISE_WINDOW'
export const SET_EDIT_EXERCISE_WINDOW = 'EXERCISES/SET_EDIT_EXERCISE_WINDOW'
export const SET_DELETE_EXERCISE_WINDOW = 'EXERCISES/SET_DELETE_EXERCISE_WINDOW'


export const SET_ALL_EXERCISES_ERROR = 'EXERCISES/SET_ALL_EXERCISES_ERROR'
export const SET_CREATE_EXERCISE_WINDOW_ERROR = 'EXERCISES/SET_CREATE_EXERCISE_WINDOW_ERROR'